using System.ComponentModel.DataAnnotations;
using Aevatar.Application.Grains.Agents.ChatManager.Common;

namespace GodGPT.GAgents.DailyPush;

/// <summary>
/// Device registration/update request for GodGPT internal use
/// </summary>
public class DeviceRequest
{
    /// <summary>
    /// Device ID generated by frontend (required)
    /// </summary>
    [Required]
    public string DeviceId { get; set; } = "";
    
    /// <summary>
    /// Firebase push token (optional for updates)
    /// </summary>
    public string? PushToken { get; set; }
    
    /// <summary>
    /// IANA timezone ID (optional for updates)
    /// </summary>
    public string? TimeZoneId { get; set; }
    
    /// <summary>
    /// Push language setting (optional for updates)
    /// </summary>
    public GodGPTLanguage? PushLanguage { get; set; }
    
    /// <summary>
    /// Push enabled/disabled switch (optional for updates)
    /// </summary>
    public bool? PushEnabled { get; set; }
}
