namespace GodGPT.GAgents.DailyPush;

/// <summary>
/// User device information for daily push notifications
/// </summary>
[GenerateSerializer]
public class UserDeviceInfo
{
    /// <summary>
    /// Device ID generated by frontend (primary key)
    /// </summary>
    [Id(0)]
    public string DeviceId { get; set; } = "";

    /// <summary>
    /// Firebase push token (can change when token refreshes)
    /// </summary>
    [Id(1)]
    public string PushToken { get; set; } = "";

    /// <summary>
    /// IANA timezone ID for device-level timezone
    /// </summary>
    [Id(2)]
    public string TimeZoneId { get; set; } = "";

    /// <summary>
    /// Push language setting for this device
    /// </summary>
    [Id(3)]
    public string PushLanguage { get; set; } = "en";

    /// <summary>
    /// Device push switch enabled/disabled
    /// </summary>
    [Id(4)]
    public bool PushEnabled { get; set; } = true;

    /// <summary>
    /// Device registration timestamp for troubleshooting
    /// </summary>
    [Id(5)]
    public DateTime RegisteredAt { get; set; }

    /// <summary>
    /// Last token update timestamp
    /// </summary>
    [Id(6)]
    public DateTime LastTokenUpdate { get; set; }
}